from pymavlink.dialects.v20 import ardupilotmega as mavlink

# Commands for COMMAND_LONG message
MIL_MISSION_CMD = mavlink.MAV_CMD_USER_1
MIL_SYSTEM_CMD = mavlink.MAV_CMD_USER_4

# System Status for heartbeat (uint8_t)
MIL_STATE_CONNECTING = 9
MIL_STATE_STANDBY = 10
MIL_STATE_OVERRIDE = 11
MIL_STATE_MISSION = 12
MIL_STATE_INITIAL_OVERRIDE = 13

MIL_STATES = {
    MIL_STATE_CONNECTING: "MIL_STATE_CONNECTING",
    MIL_STATE_STANDBY: "MIL_STATE_STANDBY",
    MIL_STATE_OVERRIDE: "MIL_STATE_OVERRIDE",
    MIL_STATE_MISSION: "MIL_STATE_MISSION",
    MIL_STATE_INITIAL_OVERRIDE: "MIL_STATE_INITIAL_OVERRIDE"
}

# System Commands
MIL_SYSTEM_PING = 0
MIL_SYSTEM_GUIDED = 1
MIL_SYSTEM_OVERRIDE = 2
MIL_SYSTEM_CANCEL = 3
MIL_SYSTEM_MAGNET = 4

MIL_SYSTEM_CMDS = {
    MIL_SYSTEM_PING: "MIL_SYSTEM_PING",
    MIL_SYSTEM_GUIDED: "MIL_SYSTEM_GUIDED",
    MIL_SYSTEM_OVERRIDE: "MIL_SYSTEM_OVERRIDE",
    MIL_SYSTEM_CANCEL: "MIL_SYSTEM_CANCEL",
    MIL_SYSTEM_MAGNET: "MIL_SYSTEM_MAGNET"
}